"""Generate SQLModel classes from DataObjectIR.

One class per table/view. Stored procedures cannot be expressed as SQLModel
classes - they are emitted as documented stubs and flagged in the ledger by
the scaffold stage.
"""
from __future__ import annotations

import re

from demagic.ir.models import DataObjectIR, magic_type_to_python

_PY_IMPORTS = {
    "Decimal": "from decimal import Decimal",
    "date": "from datetime import date",
    "time": "from datetime import time",
}


def _class_name(magic_name: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z]+", " ", magic_name).title().replace(" ", "")
    singular = cleaned[:-1] if cleaned.endswith("s") else cleaned
    return singular or "Unnamed"


def _field_name(col_name: str) -> str:
    s = re.sub(r"[^0-9A-Za-z]+", "_", col_name)
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s).lower()
    return re.sub(r"_+", "_", s).strip("_")


def generate_models(objects: list[DataObjectIR]) -> str:
    lines: list[str] = []
    needed_imports: set[str] = set()
    bodies: list[str] = []

    for obj in objects:
        if obj.object_type == "S" or obj.sp_type:
            bodies.append(
                f"# FLAGGED: stored procedure {obj.physical_name} "
                f"({obj.sp_params} params) - port manually or via translate stage.\n")
            continue

        cls = _class_name(obj.magic_name or obj.physical_name)
        pk_cols = {c for idx in obj.indexes if idx.unique for c in idx.columns}
        body = [f"class {cls}(SQLModel, table=True):",
                f'    __tablename__ = "{obj.physical_name}"',
                ""]
        for col in obj.columns:
            py_type = magic_type_to_python(col.magic_type)
            if py_type in _PY_IMPORTS:
                needed_imports.add(_PY_IMPORTS[py_type])
            fname = _field_name(col.db_name or col.name)
            if col.name in pk_cols:
                body.append(f"    {fname}: int | None = Field(default=None, primary_key=True)")
            else:
                body.append(f"    {fname}: {py_type} | None = None")
        bodies.append("\n".join(body) + "\n")

    lines.append('"""Database models generated by demagic from DataSources.xml."""')
    lines.extend(sorted(needed_imports))
    lines.append("from sqlmodel import Field, SQLModel")
    lines.append("")
    lines.append("")
    lines.append("\n\n".join(bodies))
    return "\n".join(lines)
