"""Stage 3: scaffold - generate the target FastAPI + SQLModel project."""
from __future__ import annotations

from pathlib import Path

from demagic.ir.models import ProjectIR
from demagic.ledger.ledger import ArtifactStatus, Ledger
from demagic.scaffold.models_gen import generate_models
from demagic.scaffold.uispec_gen import write_ui_specs

PENDING_MARKER = "DEMAGIC-PENDING"

_PYPROJECT = """\
[project]
name = "{name}"
version = "0.1.0"
description = "Converted from Magic xpa by demagic"
requires-python = ">=3.12"
dependencies = ["fastapi>=0.115", "sqlmodel>=0.0.22", "uvicorn>=0.30"]
"""

_MAIN_HEADER = '''\
"""FastAPI application generated by demagic."""
from fastapi import FastAPI

app = FastAPI(title="{name}")
'''

_SERVICE_TEMPLATE = '''\
"""Service for Magic program #{prog_id}: {description}

Source artifact: {artifact_id}
Logic units: {lu_count} | Expressions: {expr_count}
"""


def run() -> dict:
    """{marker}: business logic awaiting translate stage.

    Magic logic summary:
{summary}
    """
    raise NotImplementedError("{marker} prg:{prog_id}")
'''


def _summarize(prg) -> str:
    lines = []
    for lu in prg.logic_units:
        ops = ", ".join(f"{k}x{v}" for k, v in lu.operations.items()) or "none"
        lines.append(f"    - [{lu.level}] ops: {ops}; "
                     f"exprs: {[e.text for e in lu.expressions]}")
    return "\n".join(lines) or "    - (empty)"


def scaffold_project(project: ProjectIR, out_dir: Path, workdir: Path) -> None:
    out_dir = Path(out_dir)
    app_dir = out_dir / "app"
    (app_dir / "services").mkdir(parents=True, exist_ok=True)
    ledger = Ledger.load(workdir)

    (out_dir / "pyproject.toml").write_text(
        _PYPROJECT.format(name=project.name.lower()), encoding="utf-8")

    # models.py from data objects
    models_code = generate_models(project.data_objects)
    (app_dir / "models.py").write_text(models_code, encoding="utf-8")
    for obj in project.data_objects:
        if obj.object_type == "S" or obj.sp_type:
            ledger.set_status(obj.artifact_id, ArtifactStatus.FLAGGED,
                              reason="stored procedure - not expressible as SQLModel",
                              output_path=str(app_dir / "models.py"))
        else:
            ledger.set_status(obj.artifact_id, ArtifactStatus.CONVERTED,
                              output_path=str(app_dir / "models.py"))

    # one service module per program with a pending marker
    headers = {h.prog_id: h for h in project.program_headers}
    routes: list[str] = []
    for prg in project.programs:
        header = headers.get(prg.prog_id)
        desc = header.description if header else (
            prg.task_descriptions[0] if prg.task_descriptions else "")
        expr_count = sum(len(lu.expressions) for lu in prg.logic_units)
        code = _SERVICE_TEMPLATE.format(
            prog_id=prg.prog_id, description=desc, artifact_id=prg.artifact_id,
            lu_count=len(prg.logic_units), expr_count=expr_count,
            summary=_summarize(prg), marker=PENDING_MARKER)
        (app_dir / "services" / f"prg_{prg.prog_id}.py").write_text(code, encoding="utf-8")

        if header and header.public_name:
            routes.append(
                f'\n\n@app.get("/{header.public_name}")\n'
                f"def {header.public_name}() -> dict:\n"
                f'    """{desc} (Magic program #{prg.prog_id})."""\n'
                f"    from app.services.prg_{prg.prog_id} import run\n"
                f"    return run()\n")

    (app_dir / "__init__.py").write_text("", encoding="utf-8")
    (app_dir / "services" / "__init__.py").write_text("", encoding="utf-8")
    (app_dir / "main.py").write_text(
        _MAIN_HEADER.format(name=project.name) + "".join(routes), encoding="utf-8")

    # UI specs; forms count as covered once their spec exists
    written = write_ui_specs(project.programs, out_dir / "ui-specs")
    for artifact_id, path in written.items():
        ledger.set_status(artifact_id, ArtifactStatus.CONVERTED, output_path=path)

    # menus are navigation metadata -> covered by the UI spec bundle
    def mark_menu(entry) -> None:
        ledger.set_status(entry.artifact_id, ArtifactStatus.CONVERTED,
                          output_path=str(out_dir / "ui-specs"))
        for child in entry.children:
            mark_menu(child)
    for menu in project.menus:
        mark_menu(menu)

    ledger.save()
